baseurl: ""
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/
  - scope:
      path: ""
    values:
      layout: "page"
#domain: "shw3512.github.io"
#repository: "shw3512.github.io"
remote_theme: pages-themes/midnight@v0.1.1
url: "https://shw3512.github.io"
